schema_version = "1.0.0"
id = "homemaker"
version = "0.0.999999"
name = "Homemaker Topologise"
tagline = "Design buildings the pointy-clicky way."
maintainer = "Bruno Postle <bruno@postle.net>"
type = "add-on"
permissions = ["files"]
website = "https://github.com/brunopostle/homemaker-addon/"
tags = ["Object"]
blender_version_min = "3.5.0"
license = ["SPDX:GPL-3.0-or-later"]
