schema_version = "1.0.0"
id = "homemaker"
version = "0.0.1"
name = "Homemaker"
tagline = "Design buildings the pointy-clicky way"
maintainer = "Bruno Postle <bruno@postle.net>"
type = "add-on"
website = "https://github.com/brunopostle/homemaker-addon/"
tags = ["Object"]
platforms = ["windows-x64", "macos-arm64", "linux-x64"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
wheels = [
  "./wheels/PyYAML-6.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
  "./wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl",
  "./wheels/PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/topologic_core-6.0.3-cp311-cp311-linux_x86_64.whl",
  "./wheels/topologic_core-6.0.3-cp311-cp311-win_amd64.whl",
  "./wheels/topologic_core-6.0.3-cp311-cp311-macosx_11_0_arm64.whl",
]
[permissions]
files = "Read asset and style files from disk"
